# Generated by Django 5.2.6 on 2025-09-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='card_holder',
        ),
        migrations.RemoveField(
            model_name='card',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'MasterCard'), ('uzcard', 'UzCard')], max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='currency',
            field=models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD'), ('EUR', 'EUR')], default='UZS', max_length=3),
        ),
    ]
